#!/bin/bash
. "$(dirname "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
  echo "$changed_files" | grep -E --quiet "$1" && eval "$2"
}

# `npm install` and `npm prune` if the `package.json` file gets changed
# to update all the nodejs ( grunt ) dependencies deleting the unused packages (not listed into the  `package.json` file)
if check_run package.json; then
	echo "package.json has changed. Installing"
	npm install && npm prune
fi

if check_run templates/default/src/images/; then
	echo "images has changed. Compile"
    rimraf ./templates/default/dist/images/ && gulp images
fi

rimraf ./templates/default/dist/css/ && rimraf ./templates/default/dist/js/ && rimraf ./node_modules/.cache/ && gulp scss && gulp js
